_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 55
            "2":
                - 1
                - 11
                - 49
                - 51
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.7
            "5": 0.19.6
            "6": 4.48.2
            "8":
                - 5
            "12": 0.19.6
            "13": darwin-arm64
batch_size:
    value: 4
dev_path:
    value: data/DuReaderQG/dev.json
fast_test:
    value: true
learning_rate:
    value: 0.0005
max_length:
    value: 512
max_samples:
    value: 10
model_id:
    value: langboat/mengzi-t5-base
num_epochs:
    value: 2
output_dir:
    value: qa_model
resume_from:
    value: null
save_steps:
    value: 5
train_path:
    value: data/DuReaderQG/train.json
wandb_entity:
    value: null
wandb_name:
    value: null
wandb_project:
    value: t5-qa
warmup_steps:
    value: 10
